language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - export APP_ENV=testing
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - npm install -g vendor/efficiently/larasset
  - php artisan server &
  - sleep 5
  - phantomjs --webdriver=4444 &
  - sleep 5

script:
  - ./vendor/bin/codecept run acceptance --env=php
  - ./vendor/bin/codecept run acceptance --env=phantom
