language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - export APP_ENV=testing
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - chmod +x ./vendor/bin/codecept # useful ?
  - npm install vendor/efficiently/larasset
  - php artisan larasset-serve &
  - sleep 3
  - php artisan serve &
  - sleep 4
  - phantomjs --webdriver=4444 &
  - sleep 4

script:
  - ./vendor/bin/codecept run acceptance --env=phantom
