language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

install: travis_retry composer install --prefer-source --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - java -jar selenium-server-standalone-2.43.1.jar -port 4444 &
  - npm install -g larasset-js
  - chmod +x ./ci_script

script: ./ci_script
