language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - export APP_ENV=testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - npm install -g vendor/efficiently/larasset
  - php artisan server &
  - sleep 5

script:
  - ./vendor/bin/codecept run acceptance --env=php
  - ./vendor/bin/codecept run acceptance --env=phantom
  - ./vendor/bin/codecept run acceptance --env=firefox
  - killall php node # Kill the Laravel and Larasset servers
  - export ASSETS_ENV=$APP_ENV # Simulate production environment for Larasset
  - php artisan larasset:precompile --environment $APP_ENV
  - php artisan serve &# Run only the Laravel server because the assets are now precompiled
  - sleep 4
  - ./vendor/bin/codecept run acceptance --env=php
  - ./vendor/bin/codecept run acceptance --env=phantom
  - ./vendor/bin/codecept run acceptance --env=firefox
